set pointsize 2

# BLUE   -> #0066CC (light: #0099FF - dark: #003366)
# RED    -> #993333
# GREEN  -> #669900 (light: #00CC66)
# PURPLE -> #663399
# ORANGE -> #CC6633 (light: #FFCC00)

# OF-LF
set style line 1 lt 1 lc rgb "#0099FF" lw 2 pt 9  ps 1.75 dt 1
# OF-WF
set style line 2 lt 1 lc rgb "#0033CC" lw 2 pt 11 ps 1.75 dt 1
# ESTM
set style line 3 lt 1 lc rgb "#00CC66" lw 2 pt 13 ps 1.5 dt 1
# TL2
set style line 4 lt 1 lc rgb "#993333" lw 2 pt 5  ps 1.5 dt 1
# Tiny STM
set style line 5 lt 1 lc rgb "#333333" lw 2 pt 7  ps 1.5 dt 1
# Custom 1
set style line 6 lt 1 lc rgb "#CC6633" lw 2 pt 2  ps 1.5 dt 1
# Custom 2
set style line 7 lt 1 lc rgb "#663399" lw 2 pt 3  ps 1.5 dt 1
# Custom 3
set style line 8 lt 1 lc rgb "#000000" lw 2 pt 1  ps 1.5 dt 1
# Natarajan
set style line 9 lt 1 lc rgb "#CC6633" lw 2 pt 4  ps 1.25 dt 1


pat1 = 'fs solid 0.5 lc rgb "#FFCC00"'
pat2 = 'fs solid 0.5 lc rgb "#00CC66"'
pat3 = 'fs solid 0.7 lc rgb "#0066CC"'
pat4 = 'fs solid 1.0 lc rgb "#993333"'
pat5 = 'fs solid 1.0 lc rgb "#333333"'
#pat5 = 'fs pattern 2 lc rgb "#0066CC"'
#pat6 = 'fs pattern 6 lc rgb "#0066CC"'
#pat5 = 'fs pattern 2 lc rgb "#000000"'
#pat6 = 'fs pattern 6 lc rgb "#000000"'

#pat1 = 'fs solid 0.0  lc rgb "#000000"'
#pat2 = 'fs solid 0.3  lc rgb "#000000"'
#pat3 = 'fs solid 0.65 lc rgb "#000000"'
#pat4 = 'fs solid 1.0  lc rgb "#000000"'
#pat5 = 'fs pattern 2  lc rgb "#000000"'
#pat6 = 'fs pattern 6  lc rgb "#000000"'
#pat7 = 'fs solid 0.5  lc rgb "#000000"'
